# This is the default snpit config.
#
# ALL system specific stuff should go under the "system" config.  That
# includes base paths, and anything you would change when moving from
# one system to another system.  Everything else is the stuff that is
# the same from one system to the next.  Ideally, this config will
# completely capture the configuration of your package, so that running
# a given version on the same input files with the same config on a
# different system, with *only* things under system having changed, will
# yield the same output.

replaceable_preloads:
  - snpit_system_config.yaml


photometry:
  phrosty:
    force_sky_subtract: true
    keep_intermediate: true
    remove_temp_dir: false
    mem_trace: false
    kerpolyorder: 2

    sfft:
      radius_cut_detmask: 2

    psf:
      type: ou24PSF
      params: {}
    
