# This the config for the NOV2025 SNPIT pipeline run if you're running
# in a contaner.  It assumes you've mounted several directories at
# specific places.
#
# NEEDED SETUP
#
# First, make yourself a temporary directory:
#
#    mkdir $SCRATCH/snpit_temp#
#
# Next, you will need to create a secrets directory under your
# home directory and put the database password
#
#   cd $HOME
#   mkdir secrets
#   chmod 710 secrets
#   setfacl -Rdm g::x,o::- secrets
#   cat > secrets/roman_snpit_ou2024_nov_ou2024nov
#   <paste the password you got from Rob here>
#
# After you've done that, hit CTRL-D and you should be back at the shell
# prompt.
#
# RUNNING THE CONTAINER
#
# cd to a directory where you want to work.  There, check out the repos
# you want to work with.
#
# In that directory, run
#
#   bash /global/cfs/cdirs/
#
# IF YOU HAVE YOUR OWN CONFIG
#
# If you have your own config options you need to set, put them in a
# .yaml file.  At the top of that .yaml file, add:
#
#   preloads
#    - /config/nov2025_container_config.yaml
#
# Then set the env var SNPIT_CONFIG (inside the container) to point to
# your .yaml file.

system:
  db:
    url: https://c3-sn.lbl.gov/roman_snpit_nov2025
    username: ou2024nov
    # LEAVE PASSWORD AS null.  Do NOT edit this field to put in a password!  Just use passwordfile
    password: null
    passwordfile: /secrets/roman_snpit_ou2024_nov_ou2024nov

  paths:
    spectra1d: /data/spectra1d
    lightcurves: /data/lightcurves
    segmaps: /data/segmaps
    images: /data/images

    temp_dir: /snpit_temp

    snappl:
      A25ePSF_path: /a25epsf

  ou24:
    simdex_server: https://roman-desc-simdex.rknop.net
    tds_base: /ou2024/RomanTDS
    config_file: /home/environment/ou2024_tds.yaml
    sn_truth_dir: /ou2024_snana
    images: /ou2024/RomanTDS/images/simple_model
    sims_sed_library: /ou2024_sims_sed_library
