# This is intended to be a standalone docker test environment that can
# run locally, or on github CI.  It has a backend database and database
# web server running, based on the current main of roman-snpit-db
#
# To use this environment, see the docs at:
#   (TODO, put in doc url.)

services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
        - "8025:8025"

  postgres:
    image: ${DB_DOCKER_ARCHIVE:-ghcr.io/roman-supernova-pit}/snpit-db-postgres:${DB_DOCKER_VERSION:-test20260812a}
    build:
      context: ../../snappl/docker/postgres
      target: postgres
    environment:
      PGPASSWDFILE: /secrets/roman_snpit_test_env_pgpasswd
      PGPASSWDFILE_RO: /secrets/roman_snpit_test_env_pgpasswd_ro
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postrgresql/data
      - type: bind
        source: secrets
        target: /secrets
        read_only: true
    healthcheck:
      test: netcat -w 1 localhost 5432 || exit 1
      interval: 5s
      timeout: 10s
      retries: 10

  createdb:
    depends_on:
      postgres:
        condition: service_healthy
    image: ${DB_DOCKER_ARCHIVE:-ghcr.io/roman-supernova-pit}/snpit-db-webserver-test:${DB_DOCKER_VERSION:-test20260812a}
    build:
      context: ../../snappl/
      dockerfile: docker/webserver/Dockerfile
      target: test
    environment:
      - SNPIT_CONFIG=/roman-snpit-db/config-test.yaml
    entrypoint:
      - python
      - -c
      - "import snappl.db.migrations.apply_migrations as a; a.apply_migrations()"

  webserver:
    depends_on:
      createdb:
        condition: service_completed_successfully
      mailhog:
        condition: service_started
    healthcheck:
      test: netcat -w 1 localhost 8080 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
    image: ${DB_DOCKER_ARCHIVE:-ghcr.io/roman-supernova-pit}/snpit-db-webserver-test:${DB_DOCKER_VERSION:-test20260812a}
    build:
      context: ../../snappl/
      dockerfile: docker/webserver/Dockerfile
      target: test
    environment:
      - SNPIT_CONFIG=/roman-snpit-db/config-test.yaml
    ports:
      - "8080:8080"
    user: ${USERID:-0}:${GROUPID:-0}


  shell:
    image: ${ENV_DOCKER_ARCHIVE:-ghcr.io/roman-supernova-pit}/roman-snpit-env:${WHICHENV:-cpu}-${DB_DOCKER_VERSION:-test20260812a}
    build:
      context: ../
      dockerfile: docker/Dockerfile
      # NOTE : this needs to be changed to snpit_dev_env if WHICHENV is cpu-dev or cuda-dev!
      target: snpit_env
      args:
        # NOTE : this needs to be changed to cuda if WHICENV is cuda or cuda-dev!
        IMAGE_TYPE: cpu
    environment:
      CRDS_SERVER_URL: https://roman-crds.stsci.edu
      CRDS_PATH: /tmp
    volumes:
      - type: volume
        source: dev_storage
        target: /dev_storage
      - type: bind
        source: secrets
        target: /secrets
        read_only: true
      - type: bind
        source: ../../
        target: /home
    working_dir: /home
    command: tail -f /etc/issue

volumes:
  postgres_data:
  dev_storage:
