# This configuration information is not needed by most procesess, it's
# *only* needed by the webserver process.  (It's also used by
# the snappl tests, and may be used by some other tests.)
#
# It should not be included anywhere in production other than in the
# webserver.
system:
  db:
    postgres_host: postgres
    postgres_port: 5432
    postgres_database: roman_snpit
    postgres_username: postgres
    postgres_password: null
    postgres_password_file: /secrets/roman_snpit_test_env_pgpasswd
    # These next two are for debugging purposes and should always be false in production
    echoqueries: true
    alwaysexplain: false
