db:
  postgres_host: postgres
  postgres_port: 5432
  postgres_database: roman_snpit
  postgres_username: postgres
  postgres_password: null
  postgres_password_file: /secrets/pgpasswd
  # These next two are for debugging purposes and should always be false in production
  echoqueries: true
  alwaysexplain: false
