# THis is a config file for using ou2024 without a database
# I'm not sure it's actually used, and we should probably delete it?
# cf: ou2024_container_config.yaml

system:
  # General OpenUniverse 2024 configurations
  ou24:
    simdex_server: https://roman-desc-simdex.lbl.gov

    tds_base: /ou2024/RomanTDS
    config_file: /ou2024/RomanTDS/tds.yaml
    sn_truth_dir: /ou2024_snana
    images: /ou2024/RomanTDS/images/simple_model
    sims_sed_library: /ou2024_sims_sed_library
